using Content.Shared._Persistence.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.Radio;

[GenerateTypedNameReferences]
public sealed partial class FactionHeadsetWindow : DefaultWindow
{
    public event Action<int>? OnTransmit;
    public event Action<int>? OnReceive;

    private readonly List<int> _factions = new();

    public FactionHeadsetWindow()
    {
        RobustXamlLoader.Load(this);

        TransmitOptions.OnItemSelected += args => OnTransmit?.Invoke(_factions[args.Id]);
        ReceiveOptions.OnItemSelected += args => OnReceive?.Invoke(_factions[args.Id]);
    }

    public void UpdateState(FactionHeadsetBoundUserInterfaceState state)
    {
        _factions.Clear();
        _factions.Add(0);
        _factions.AddRange(state.Factions.Keys);

        Fill(TransmitOptions, state, "faction-headset-window-keys", state.TransmitTo);
        Fill(ReceiveOptions, state, "faction-headset-window-all", state.ReceiveFrom);
    }

    private void Fill(OptionButton button, FactionHeadsetBoundUserInterfaceState state, string noneLoc, int selected)
    {
        button.Clear();
        for (var i = 0; i < _factions.Count; i++)
        {
            button.AddItem(i == 0 ? Loc.GetString(noneLoc) : state.Factions[_factions[i]], i);
            if (_factions[i] == selected)
                button.SelectId(i);
        }
    }
}
