using System.Linq;
using Content.Shared._Persistence.Invoices;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.Invoices;

[GenerateTypedNameReferences]
public sealed partial class InvoicePrinterWindow : DefaultWindow
{
    public event Action<BoundUserInterfaceMessage>? OnMessage;

    private static readonly InvoicePrinterMode[] Modes = Enum.GetValues<InvoicePrinterMode>();
    private readonly List<int> _factions = new();

    public InvoicePrinterWindow()
    {
        RobustXamlLoader.Load(this);

        for (var i = 0; i < Modes.Length; i++)
        {
            ModeOptions.AddItem(Loc.GetString($"invoice-printer-mode-{Modes[i].ToString().ToLowerInvariant()}"), i);
        }

        ModeOptions.OnItemSelected += args => OnMessage?.Invoke(new InvoicePrinterSetModeMessage(Modes[args.Id]));
        FactionOptions.OnItemSelected += args => OnMessage?.Invoke(new InvoicePrinterSelectStationMessage(_factions[args.Id]));
        AmountSpinBox.IsValid = value => value >= 0;
        PrintButton.OnPressed += _ =>
        {
            if (AmountSpinBox.Value <= 0)
                return;

            OnMessage?.Invoke(new InvoicePrinterPrintMessage(TitleEdit.Text, ReasonEdit.Text, AmountSpinBox.Value));
        };
    }

    public void UpdateState(InvoicePrinterConsoleBoundUserInterfaceState state)
    {
        PrivilegedIdButton.Text = state.IdName ?? string.Empty;
        ModeOptions.SelectId(Array.IndexOf(Modes, state.Mode));

        var factionMode = state.Mode != InvoicePrinterMode.PersonalInvoice;
        FactionRow.Visible = factionMode;
        _factions.Clear();
        FactionOptions.Clear();
        foreach (var (id, name) in state.Factions.OrderBy(f => f.Value))
        {
            FactionOptions.AddItem(name, _factions.Count);
            if (id == state.SelectedStation)
                FactionOptions.SelectId(_factions.Count);

            _factions.Add(id);
        }

        var selected = state.Factions.GetValueOrDefault(state.SelectedStation);
        PayToLabel.Text = state.Mode switch
        {
            InvoicePrinterMode.PersonalInvoice => Loc.GetString("invoice-printer-window-pay-to",
                ("name", state.HolderName ?? Loc.GetString("invoice-printer-window-insert-id"))),
            InvoicePrinterMode.FactionInvoice => Loc.GetString("invoice-printer-window-pay-to",
                ("name", selected ?? Loc.GetString("invoice-printer-window-select-faction"))),
            _ => Loc.GetString("invoice-printer-window-paid-by",
                ("name", selected ?? Loc.GetString("invoice-printer-window-select-faction"))),
        };

        TaxLabel.Visible = state.Mode != InvoicePrinterMode.FactionPayslip && state.TaxRate > 0;
        TaxLabel.Text = Loc.GetString("invoice-printer-window-tax",
            ("rate", state.TaxRate),
            ("faction", state.TaxingFaction ?? string.Empty));

        PrintButton.Disabled = state.HolderName == null
                               || factionMode && !state.Factions.ContainsKey(state.SelectedStation);
    }
}
