using Content.Shared._Persistence.Invoices;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Persistence.Invoices;

[GenerateTypedNameReferences]
public sealed partial class InvoiceWindow : DefaultWindow
{
    public event Action<int>? OnPay;

    private readonly List<int> _sources = new();

    public InvoiceWindow()
    {
        RobustXamlLoader.Load(this);

        PayFromOptions.OnItemSelected += args => PayFromOptions.SelectId(args.Id);
        PayButton.OnPressed += _ =>
        {
            if (PayFromOptions.SelectedId >= 0 && PayFromOptions.SelectedId < _sources.Count)
                OnPay?.Invoke(_sources[PayFromOptions.SelectedId]);
        };
    }

    public void UpdateState(InvoiceBoundUserInterfaceState state)
    {
        Title = Loc.GetString(state.Payslip ? "invoice-window-payslip-title" : "invoice-window-title");
        AmountLabel.Text = Loc.GetString("invoice-window-amount", ("amount", state.Cost));
        PayToLabel.Text = Loc.GetString(state.Payslip ? "invoice-window-paid-by-faction" : "invoice-window-pay-to",
            ("name", state.PayTo));
        TaxLabel.Visible = state.TaxRate > 0;
        TaxLabel.Text = Loc.GetString("invoice-window-tax", ("rate", state.TaxRate));
        ReasonLabel.SetMessage(FormattedMessage.FromUnformatted(state.Reason));

        PaidLabel.Visible = state.Paid;
        PaidLabel.Text = Loc.GetString(state.Payslip ? "invoice-window-redeemed" : "invoice-window-paid",
            ("by", state.PaidBy),
            ("time", state.PaidTime?.ToString("g") ?? string.Empty));
        PaySection.Visible = !state.Paid;
        if (state.Paid)
            return;

        CreditsLabel.Text = Loc.GetString("invoice-window-credits", ("credits", state.Credits));
        PayButton.Text = Loc.GetString(state.Payslip ? "invoice-window-redeem" : "invoice-window-pay");

        _sources.Clear();
        PayFromOptions.Clear();
        PayFromOptions.AddItem(Loc.GetString(state.Payslip ? "invoice-window-to-credits" : "invoice-window-from-credits"), 0);
        _sources.Add(0);
        foreach (var (id, name) in state.Factions)
        {
            PayFromOptions.AddItem(name, _sources.Count);
            _sources.Add(id);
        }
    }
}
