using Content.Shared._Persistence.Factions.Prototypes;
using Content.Shared._Persistence.JobNet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence.JobNet;

[GenerateTypedNameReferences]
public sealed partial class JobNetWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _proto = null!;

    public event Action<int>? OnSelect;
    public event Action? OnPurchase;

    private readonly List<int> _stations = new();

    public JobNetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("jobnet-window-tab-work"));
        Tabs.SetTabTitle(1, Loc.GetString("jobnet-window-tab-network"));

        StationOptions.OnItemSelected += args => OnSelect?.Invoke(_stations[args.Id]);
        PurchaseButton.OnPressed += _ => OnPurchase?.Invoke();
    }

    public void UpdateState(JobNetUpdateState state)
    {
        _stations.Clear();
        StationOptions.Clear();
        StationOptions.AddItem(Loc.GetString("jobnet-window-off-duty"), 0);
        _stations.Add(0);
        foreach (var (id, name) in state.Stations)
        {
            StationOptions.AddItem(name, _stations.Count);
            if (id == state.SelectedStation)
                StationOptions.SelectId(_stations.Count);

            _stations.Add(id);
        }

        NoFactionsLabel.Visible = state.Stations.Count == 0;

        var working = state.AssignmentName != null;
        AssignmentLabel.Visible = working;
        WageLabel.Visible = working;
        NextPayLabel.Visible = working;
        SpendingLabel.Visible = working && state.SpendAuth;
        if (working)
        {
            AssignmentLabel.Text = Loc.GetString("jobnet-window-assignment", ("assignment", state.AssignmentName!));
            WageLabel.Text = Loc.GetString("jobnet-window-wage", ("wage", state.Wage ?? 0));
            NextPayLabel.Text = Loc.GetString("jobnet-window-next-pay",
                ("time", state.RemainingTime.ToString(@"mm\:ss")));
            SpendingLabel.Text = state.IsOwner
                ? Loc.GetString("jobnet-window-spending-unlimited")
                : Loc.GetString("jobnet-window-spending", ("spent", state.Spent), ("limit", state.Spendable));
        }

        BalanceLabel.Text = Loc.GetString("jobnet-window-balance", ("balance", state.Balance));

        if (!_proto.Resolve(state.Level, out NetworkLevelPrototype? level))
            return;

        LevelLabel.Text = Loc.GetString("jobnet-window-level", ("level", Loc.GetString(level.Name)));
        TileLimitLabel.Text = Loc.GetString("jobnet-window-tile-limit", ("limit", level.TileLimit));

        NetworkLevelPrototype? next = null;
        if (level.Next is { } nextId)
            _proto.Resolve(nextId, out next);

        PurchaseButton.Visible = next != null;
        if (next == null)
        {
            NextLevelLabel.Text = Loc.GetString("jobnet-window-max-level");
            return;
        }

        NextLevelLabel.Text = Loc.GetString("jobnet-window-next-level",
            ("level", Loc.GetString(next.Name)),
            ("limit", next.TileLimit));
        PurchaseButton.Text = Loc.GetString("jobnet-window-purchase", ("cost", next.Cost));
        PurchaseButton.Disabled = state.Balance < next.Cost;
    }
}
