using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.GridControl;

[GenerateTypedNameReferences]
public sealed partial class GridControlConsoleWindow : DefaultWindow
{
    public event Action<bool>? OnSetActive;

    public GridControlConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        OnButton.OnPressed += _ => OnSetActive?.Invoke(true);
        OffButton.OnPressed += _ => OnSetActive?.Invoke(false);
    }

    public void UpdateState(bool active)
    {
        OnButton.Pressed = active;
        OffButton.Pressed = !active;
    }
}
