using System.Linq;
using Content.Shared._Persistence.GridControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.GridControl;

[GenerateTypedNameReferences]
public sealed partial class GridConfigWindow : DefaultWindow
{
    public event Action<BoundUserInterfaceMessage>? OnMessage;

    private readonly List<int> _targets = new();

    public GridConfigWindow()
    {
        RobustXamlLoader.Load(this);

        FactionModeButton.OnPressed += _ => OnMessage?.Invoke(new GridConfigChangeMode());
        PersonalModeButton.OnPressed += _ => OnMessage?.Invoke(new GridConfigChangeMode());
        PossibleTargets.OnItemSelected += args => OnMessage?.Invoke(new GridConfigTargetSelect(_targets[args.Id]));
        ClaimButton.OnPressed += _ => OnMessage?.Invoke(new GridConfigConnect());
        UnclaimButton.OnPressed += _ => OnMessage?.Invoke(new GridConfigDisconnect());
        GridNameButton.OnPressed += _ =>
        {
            if (GridNameLineEdit.Text.Trim().Length > 0)
                OnMessage?.Invoke(new GridConfigChangeName(GridNameLineEdit.Text));
        };
    }

    public void UpdateState(GridConfigBoundUserInterfaceState state)
    {
        PrivilegedIdButton.Text = state.IdName ?? string.Empty;

        FactionModeButton.Pressed = !state.PersonalMode;
        PersonalModeButton.Pressed = state.PersonalMode;
        PossibleTargets.Visible = !state.PersonalMode;
        if (state.PersonalMode)
        {
            TargetNameLabel.Text = Loc.GetString("grid-config-window-target-person",
                ("name", state.TargetName ?? Loc.GetString("grid-config-window-none")));
        }
        else
        {
            TargetNameLabel.Text = Loc.GetString("grid-config-window-target-faction");
            _targets.Clear();
            PossibleTargets.Clear();
            PossibleTargets.AddItem(Loc.GetString("grid-config-window-none"), 0);
            _targets.Add(0);
            foreach (var (id, name) in state.PossibleStations.OrderBy(s => s.Value))
            {
                PossibleTargets.AddItem(name, _targets.Count);
                if (id == state.TargetStation)
                    PossibleTargets.SelectId(_targets.Count);

                _targets.Add(id);
            }
        }

        GridSizeLabel.Text = Loc.GetString("grid-config-window-grid-size", ("size", state.GridTileCount));
        AvailableLabel.Visible = state.TargetName != null;
        AvailableLabel.Text = Loc.GetString("grid-config-window-available",
            ("available", Math.Max(0, state.TileLimit - state.CurrentTileCount)),
            ("limit", state.TileLimit));

        var gridFound = state.GridName != null;
        var owned = state.OwnerName != null;
        GridNameLabel.Text = Loc.GetString("grid-config-window-grid-name",
            ("name", state.GridName ?? Loc.GetString("grid-config-window-invalid-grid")));
        GridOwnerLabel.Text = Loc.GetString("grid-config-window-owner",
            ("owner", state.OwnerName ?? Loc.GetString("grid-config-window-unclaimed")));

        ErrorLabel.Text = !gridFound ? Loc.GetString("grid-config-no-grid")
            : state.IdName != null && !state.IsAuth ? Loc.GetString("grid-config-not-authorized")
            : owned && state.IsControlled ? Loc.GetString("grid-config-controlled")
            : state.ErrorMessage ?? string.Empty;

        ClaimButton.Disabled = !gridFound || owned || !state.IsAuth || state.ErrorMessage != null;
        UnclaimButton.Disabled = !gridFound || !owned || !state.IsAuth || state.IsControlled;
        GridNameButton.Disabled = !gridFound || !owned || !state.IsAuth;
    }
}
