using System.Linq;
using Content.Shared._Persistence.GridControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.GridControl;

[GenerateTypedNameReferences]
public sealed partial class StationTaggerWindow : DefaultWindow
{
    public event Action<BoundUserInterfaceMessage>? OnMessage;

    private readonly List<int> _targets = new();

    public StationTaggerWindow()
    {
        RobustXamlLoader.Load(this);

        PossibleTargets.OnItemSelected += args => OnMessage?.Invoke(new StationTaggerTargetSelect(_targets[args.Id]));
        LinkButton.OnPressed += _ => OnMessage?.Invoke(new StationTaggerLink());
        UnlinkButton.OnPressed += _ => OnMessage?.Invoke(new StationTaggerUnlink());
    }

    public void UpdateState(StationTaggerBoundUserInterfaceState state)
    {
        PrivilegedIdButton.Text = state.IdName ?? string.Empty;

        _targets.Clear();
        PossibleTargets.Clear();
        PossibleTargets.AddItem(Loc.GetString("grid-config-window-none"), 0);
        _targets.Add(0);
        foreach (var (id, name) in state.PossibleStations.OrderBy(s => s.Value))
        {
            PossibleTargets.AddItem(name, _targets.Count);
            if (id == state.TargetStation)
                PossibleTargets.SelectId(_targets.Count);

            _targets.Add(id);
        }

        TargetNameLabel.Text = state.TargetName != null
            ? Loc.GetString("station-tagger-window-target", ("name", state.TargetName))
            : Loc.GetString("station-tagger-window-no-target");
        CurrentLabel.Text = Loc.GetString("station-tagger-window-current",
            ("faction", state.TaggedFaction ?? Loc.GetString("station-tagger-window-none")));
        ErrorLabel.Text = state.TargetName != null && state.IdName != null && !state.IsAuthorized
            ? Loc.GetString("station-tagger-window-not-authorized")
            : string.Empty;

        var canEdit = state.TargetName != null && state.IsAuthorized;
        LinkButton.Disabled = !canEdit || state.TaggedFaction != null || state.TargetStation == null;
        UnlinkButton.Disabled = !canEdit || state.TaggedFaction == null;
    }
}
