using Content.Shared._Persistence.GridControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.GridControl;

[GenerateTypedNameReferences]
public sealed partial class StationCreatorWindow : DefaultWindow
{
    public event Action<string>? OnFinish;

    public StationCreatorWindow()
    {
        RobustXamlLoader.Load(this);

        FinishButton.OnPressed += _ =>
        {
            if (StationNameLineEdit.Text.Trim().Length > 0)
                OnFinish?.Invoke(StationNameLineEdit.Text);
        };
    }

    public void UpdateState(StationCreatorBoundUserInterfaceState state)
    {
        PrivilegedIdButton.Text = state.IdName ?? string.Empty;
        OwnerLabel.Text = state.RealName != null
            ? Loc.GetString("station-creator-window-owner", ("owner", state.RealName))
            : Loc.GetString("station-creator-window-no-owner");
        FinishButton.Disabled = state.RealName == null;
    }
}
