using Content.Shared._Persistence.Factions.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.Factions.UI;

/// <summary>
/// The faction tab of the ID card console.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionIdCardConsoleControl : BoxContainer
{
    public event Action<int>? OnAssign;
    public event Action? OnResetSpending;
    public event Action<FactionRecordType, string>? OnSaveRecord;
    public event Action<FactionRecordType>? OnPrintRecord;

    public FactionIdCardConsoleControl()
    {
        RobustXamlLoader.Load(this);

        FactionTabs.SetTabTitle(0, Loc.GetString("faction-id-console-tab-account"));
        FactionTabs.SetTabTitle(1, Loc.GetString("faction-id-console-tab-crew"));
        RecordTabs.SetTabTitle(0, Loc.GetString("faction-id-console-tab-assignment"));
        RecordTabs.SetTabTitle(1, Loc.GetString("faction-id-console-tab-general"));
        RecordTabs.SetTabTitle(2, Loc.GetString("faction-id-console-tab-criminal"));
        RecordTabs.SetTabTitle(3, Loc.GetString("faction-id-console-tab-medical"));

        ResetSpendingButton.OnPressed += _ => OnResetSpending?.Invoke();

        GeneralRecord.OnSave += text => OnSaveRecord?.Invoke(FactionRecordType.General, text);
        CriminalRecord.OnSave += text => OnSaveRecord?.Invoke(FactionRecordType.Criminal, text);
        MedicalRecord.OnSave += text => OnSaveRecord?.Invoke(FactionRecordType.Medical, text);
        GeneralRecord.OnPrint += () => OnPrintRecord?.Invoke(FactionRecordType.General);
        CriminalRecord.OnPrint += () => OnPrintRecord?.Invoke(FactionRecordType.Criminal);
        MedicalRecord.OnPrint += () => OnPrintRecord?.Invoke(FactionRecordType.Medical);
    }

    public void UpdateState(FactionIdCardConsoleState? state)
    {
        if (state?.FactionName == null)
        {
            FactionLabel.Text = Loc.GetString("faction-id-console-no-faction");
            StatusLabel.Visible = false;
            FactionTabs.Visible = false;
            return;
        }

        FactionLabel.Text = Loc.GetString("faction-id-console-faction", ("faction", state.FactionName));
        StatusLabel.Visible = !state.IsMember;
        StatusLabel.Text = Loc.GetString("faction-id-console-not-member");
        FactionTabs.Visible = state.IsMember;
        if (!state.IsMember)
            return;

        UpdateCrewList(state);
        UpdateSelected(state);
    }

    private void UpdateCrewList(FactionIdCardConsoleState state)
    {
        CrewList.RemoveAllChildren();
        foreach (var entry in state.Crew)
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            row.AddChild(new Label
            {
                Text = Loc.GetString("faction-id-console-crew-entry",
                    ("name", entry.Name),
                    ("assignment", entry.Assignment ?? Loc.GetString("faction-id-console-unassigned"))),
            });
            row.AddChild(new Control { HorizontalExpand = true });
            row.AddChild(new Label { Text = entry.LastPaid == DateTime.MinValue ? "-" : entry.LastPaid.ToString("g") });
            CrewList.AddChild(row);
        }
    }

    private void UpdateSelected(FactionIdCardConsoleState state)
    {
        SelectedLabel.Text = state.SelectedName ?? Loc.GetString("faction-id-console-none-selected");
        RecordTabs.Visible = state.SelectedName != null;
        if (state.SelectedName == null)
            return;

        var current = state.Assignments.GetValueOrDefault(state.SelectedAssignmentId);
        AssignmentLabel.Text = state.SelectedHasRecord
            ? current?.Name ?? Loc.GetString("faction-id-console-unassigned")
            : Loc.GetString("faction-id-console-no-record");

        SpendingLabel.Text = Loc.GetString("faction-id-console-spending",
            ("spent", state.SelectedSpent),
            ("limit", current?.SpendingLimit ?? 0));
        ResetSpendingButton.Disabled = !state.CanResetSpending;

        AssignmentGrid.RemoveAllChildren();
        AddAssignmentButton(state, 0, Loc.GetString("faction-id-console-unassigned"));
        foreach (var (id, assignment) in state.Assignments)
        {
            AddAssignmentButton(state, id, assignment.Name);
        }

        GeneralRecord.UpdateState(state.GeneralRecord, state.CanEditRecords && state.SelectedHasRecord);
        CriminalRecord.UpdateState(state.CriminalRecord, state.CanEditRecords && state.SelectedHasRecord);
        MedicalRecord.UpdateState(state.MedicalRecord, state.CanEditRecords && state.SelectedHasRecord);
    }

    private void AddAssignmentButton(FactionIdCardConsoleState state, int id, string text)
    {
        var button = new Button
        {
            Text = text,
            ToggleMode = true,
            HorizontalExpand = true,
            ClipText = true,
            Pressed = state.SelectedHasRecord && state.SelectedAssignmentId == id,
            Disabled = !state.AssignableIds.Contains(id),
        };
        button.OnPressed += _ => OnAssign?.Invoke(id);
        AssignmentGrid.AddChild(button);
    }
}
