using Content.Shared._Persistence.Factions.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.Factions.UI;

/// <summary>
/// The faction section of an access reader's configuration UI: which of the owning faction's accesses it requires,
/// and who it lets in personally.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FactionAccessReaderControl : BoxContainer
{
    public event Action<string>? OnToggleAccess;
    public event Action<bool>? OnPersonalMode;
    public event Action<string>? OnPersonalAdd;
    public event Action<string>? OnPersonalRemove;

    public FactionAccessReaderControl()
    {
        RobustXamlLoader.Load(this);

        PersonalModeCheckBox.OnToggled += args => OnPersonalMode?.Invoke(args.Pressed);
        PersonalAddButton.OnPressed += _ => SubmitName();
        PersonalNameLineEdit.OnTextEntered += _ => SubmitName();
    }

    private void SubmitName()
    {
        var name = PersonalNameLineEdit.Text.Trim();
        if (name.Length == 0)
            return;

        OnPersonalAdd?.Invoke(name);
        PersonalNameLineEdit.Text = string.Empty;
    }

    public void UpdateState(FactionAccessReaderState? state)
    {
        Visible = state != null;
        if (state == null)
            return;

        FactionLabel.Text = state.FactionName == null
            ? Loc.GetString("faction-access-reader-no-faction")
            : Loc.GetString("faction-access-reader-faction", ("faction", state.FactionName));

        FactionAccessGrid.RemoveAllChildren();
        foreach (var access in state.FactionAccesses)
        {
            var button = new Button
            {
                Text = access,
                ToggleMode = true,
                Pressed = state.RequiredAccesses.Contains(access),
                Disabled = !state.EditableAccesses.Contains(access),
            };
            button.OnPressed += _ => OnToggleAccess?.Invoke(access);
            FactionAccessGrid.AddChild(button);
        }

        NoFactionAccessesLabel.Visible = state.FactionName != null && state.FactionAccesses.Count == 0;

        PersonalModeCheckBox.Pressed = state.PersonalAccessMode;
        PersonalSection.Visible = state.PersonalAccessMode;
        PersonalNamesContainer.RemoveAllChildren();
        foreach (var name in state.PersonalAccessNames)
        {
            var row = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = name, HorizontalExpand = true });
            var remove = new Button { Text = Loc.GetString("faction-access-reader-personal-remove") };
            remove.OnPressed += _ => OnPersonalRemove?.Invoke(name);
            row.AddChild(remove);
            PersonalNamesContainer.AddChild(row);
        }
    }
}
