using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence.Factions.UI;

[GenerateTypedNameReferences]
public sealed partial class IdPrinterConsoleWindow : DefaultWindow
{
    public event Action? OnPrint;

    public IdPrinterConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        PrintButton.OnPressed += _ => OnPrint?.Invoke();
    }
}
