using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence.Factions.BUI;
using Content.Shared._Persistence.Factions.Components;
using Content.Shared._Persistence.Factions.Prototypes;
using Content.Shared.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Persistence.Factions.UI;

/// <summary>
/// The station modification console, ported from SS14-Persistence.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StationModificationMenu : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = null!;

    /// <summary>
    /// Raised with every message the menu wants sent to the console.
    /// </summary>
    public event Action<BoundUserInterfaceMessage>? OnMessage;

    private StationModificationInterfaceState? _state;
    private int? _selectedAssignment;
    private string? _pendingAssignmentName;
    private ProtoId<RadioChannelPrototype>? _selectedChannel;
    private readonly List<int> _assignmentIds = new();
    private readonly List<ProtoId<RadioChannelPrototype>> _channelIds = new();
    private readonly List<string> _accessIds = new();

    public StationModificationMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Tabs.SetTabTitle(0, Loc.GetString("station-modification-tab-general"));
        Tabs.SetTabTitle(1, Loc.GetString("station-modification-tab-assignments"));
        Tabs.SetTabTitle(2, Loc.GetString("station-modification-tab-radio"));
        Tabs.SetTabTitle(3, Loc.GetString("station-modification-tab-upgrade"));

        FactionTagField.OnTextChanged += _ =>
        {
            if (FactionTagField.Text.Length <= FactionDataComponent.MaxFactionTagLength)
                return;

            FactionTagField.Text = FactionTagField.Text[..FactionDataComponent.MaxFactionTagLength];
            FactionTagField.CursorPosition = FactionTagField.Text.Length;
        };

        StationNameConfirm.OnPressed += _ => Send(new StationModificationChangeName(StationNameField.Text));
        FactionTagConfirm.OnPressed += _ => Send(new StationModificationChangeFactionTag(FactionTagField.Text));
        NewOwnerConfirm.OnPressed += _ =>
        {
            Send(new StationModificationAddOwner(NewOwnerField.Text));
            NewOwnerField.Text = string.Empty;
        };
        AccessCreateConfirm.OnPressed += _ =>
        {
            Send(new StationModificationAddAccess(AccessCreateField.Text));
            AccessCreateField.Text = string.Empty;
        };
        DefaultAccessCreate.OnPressed += _ => Send(new StationModificationDefaultAccess());
        PossibleAccesses.OnItemSelected += args => PossibleAccesses.SelectId(args.Id);
        AccessDeleteConfirm.OnPressed += _ =>
        {
            if (PossibleAccesses.SelectedId >= 0 && PossibleAccesses.SelectedId < _accessIds.Count)
                Send(new StationModificationRemoveAccess(_accessIds[PossibleAccesses.SelectedId]));
        };
        JobNetOn.OnPressed += _ => Send(new StationModificationSetJobNet(true));
        JobNetOff.OnPressed += _ => Send(new StationModificationSetJobNet(false));
        ImportTaxConfirm.OnPressed += _ => Send(new StationModificationChangeTax(FactionTaxType.Import, ImportTaxSpinBox.Value));
        ExportTaxConfirm.OnPressed += _ => Send(new StationModificationChangeTax(FactionTaxType.Export, ExportTaxSpinBox.Value));
        SalesTaxConfirm.OnPressed += _ => Send(new StationModificationChangeTax(FactionTaxType.Sales, SalesTaxSpinBox.Value));

        PossibleAssignments.OnItemSelected += args =>
        {
            PossibleAssignments.SelectId(args.Id);
            _selectedAssignment = _assignmentIds[args.Id];
            UpdateAssignment();
        };
        AssignmentNameConfirm.OnPressed += _ =>
            SendAssignment(id => new StationModificationChangeAssignmentName(id, AssignmentNameField.Text));
        WageConfirm.OnPressed += _ =>
            SendAssignment(id => new StationModificationChangeAssignmentValue(id, AssignmentValue.Wage, WageSpinBox.Value));
        CommandLevelConfirm.OnPressed += _ =>
            SendAssignment(id => new StationModificationChangeAssignmentValue(id, AssignmentValue.CommandLevel, CommandLevelSpinBox.Value));
        SpendingLimitConfirm.OnPressed += _ =>
            SendAssignment(id => new StationModificationChangeAssignmentValue(id, AssignmentValue.SpendingLimit, SpendingLimitSpinBox.Value));
        AssignFlagButton.OnPressed += _ =>
            SendAssignment(id => new StationModificationToggleAssignmentFlag(id, AssignmentFlag.CanAssign));
        ClaimFlagButton.OnPressed += _ =>
            SendAssignment(id => new StationModificationToggleAssignmentFlag(id, AssignmentFlag.CanClaim));
        RecordsFlagButton.OnPressed += _ =>
            SendAssignment(id => new StationModificationToggleAssignmentFlag(id, AssignmentFlag.CanEditRecords));
        DeleteAssignmentButton.OnPressed += _ =>
            SendAssignment(id => new StationModificationDeleteAssignment(id));
        CreateAssignmentButton.OnPressed += _ =>
        {
            _pendingAssignmentName = NewAssignmentNameField.Text.Trim();
            Send(new StationModificationCreateAssignment(NewAssignmentNameField.Text));
            NewAssignmentNameField.Text = string.Empty;
        };

        PossibleChannels.OnItemSelected += args =>
        {
            PossibleChannels.SelectId(args.Id);
            _selectedChannel = _channelIds[args.Id];
            UpdateChannel();
        };
        ChannelEnable.OnPressed += _ => SendChannel(id => new StationModificationSetChannelEnabled(id, true));
        ChannelDisable.OnPressed += _ => SendChannel(id => new StationModificationSetChannelEnabled(id, false));

        LevelPurchaseButton.OnPressed += _ => Send(new StationModificationPurchaseUpgrade());

        // Don't let negative values get as far as the server.
        foreach (var spin in new[] { ImportTaxSpinBox, ExportTaxSpinBox, SalesTaxSpinBox, WageSpinBox, CommandLevelSpinBox, SpendingLimitSpinBox })
        {
            spin.IsValid = value => value >= 0;
        }
    }

    private void Send(BoundUserInterfaceMessage message)
    {
        OnMessage?.Invoke(message);
    }

    private void SendAssignment(Func<int, BoundUserInterfaceMessage> message)
    {
        if (_selectedAssignment is { } id)
            Send(message(id));
    }

    private void SendChannel(Func<ProtoId<RadioChannelPrototype>, BoundUserInterfaceMessage> message)
    {
        if (_selectedChannel is { } id)
            Send(message(id));
    }

    public void UpdateState(StationModificationInterfaceState state)
    {
        NoFactionLabel.Visible = !state.HasFaction;
        Tabs.Visible = state.HasFaction;
        StationNameLabel.Visible = state.HasFaction;
        if (!state.HasFaction)
            return;

        _state = state;

        StationNameLabel.Text = state.Name;
        StationNameField.Text = state.Name;
        FactionTagField.Text = state.FactionTag;

        UpdateOwners(state);
        UpdateAccesses(state);

        JobNetOn.Pressed = state.JobNetEnabled;
        JobNetOff.Pressed = !state.JobNetEnabled;

        ClaimTradeStationLabel.Visible = !state.TradeStationClaimed;
        TaxOptions.Visible = state.TradeStationClaimed;
        ImportTaxSpinBox.Value = state.ImportTax;
        ExportTaxSpinBox.Value = state.ExportTax;
        SalesTaxSpinBox.Value = state.SalesTax;

        UpdateAssignments(state);
        UpdateChannels(state);
        UpdateUpgrades(state);
    }

    private void UpdateOwners(StationModificationInterfaceState state)
    {
        OwnersList.RemoveAllChildren();
        foreach (var owner in state.Owners)
        {
            var button = new Button
            {
                Text = owner,
                ToolTip = Loc.GetString("station-modification-owner-remove-tooltip"),
            };
            button.OnPressed += _ => Send(new StationModificationRemoveOwner(owner));
            OwnersList.AddChild(button);
        }
    }

    private void UpdateAccesses(StationModificationInterfaceState state)
    {
        _accessIds.Clear();
        _accessIds.AddRange(state.CrewAccesses);
        PossibleAccesses.Clear();
        for (var i = 0; i < _accessIds.Count; i++)
        {
            PossibleAccesses.AddItem(_accessIds[i], i);
        }
    }

    private void UpdateAssignments(StationModificationInterfaceState state)
    {
        _assignmentIds.Clear();
        PossibleAssignments.Clear();
        foreach (var (id, assignment) in state.CrewAssignments.OrderBy(a => a.Key))
        {
            // Jump to an assignment as soon as it's been created.
            if (_pendingAssignmentName != null && assignment.Name == _pendingAssignmentName)
            {
                _selectedAssignment = id;
                _pendingAssignmentName = null;
            }

            PossibleAssignments.AddItem(assignment.Name, _assignmentIds.Count);
            _assignmentIds.Add(id);
        }

        if (_selectedAssignment == null || !_assignmentIds.Contains(_selectedAssignment.Value))
            _selectedAssignment = _assignmentIds.Count > 0 ? _assignmentIds[0] : (int?) null;

        if (_selectedAssignment is { } selected)
            PossibleAssignments.SelectId(_assignmentIds.IndexOf(selected));

        UpdateAssignment();
    }

    private void UpdateAssignment()
    {
        AssignmentAccesses.RemoveAllChildren();
        if (_state == null
            || _selectedAssignment is not { } id
            || !_state.CrewAssignments.TryGetValue(id, out var assignment))
        {
            AssignmentDetails.Visible = false;
            return;
        }

        AssignmentDetails.Visible = true;
        AssignmentNameField.Text = assignment.Name;
        WageSpinBox.Value = assignment.Wage;
        CommandLevelSpinBox.Value = assignment.Clevel;
        SpendingLimitSpinBox.Value = assignment.SpendingLimit;
        AssignFlagButton.Pressed = assignment.CanAssign;
        ClaimFlagButton.Pressed = assignment.CanClaim;
        RecordsFlagButton.Pressed = assignment.CanEditGeneralRecord;

        foreach (var access in _state.CrewAccesses)
        {
            var button = new Button
            {
                Text = access,
                ToggleMode = true,
                ClipText = true,
                HorizontalExpand = true,
                Pressed = assignment.AccessIDs.Contains(access),
            };
            button.OnToggled += args => Send(new StationModificationSetAssignmentAccess(id, access, args.Pressed));
            AssignmentAccesses.AddChild(button);
        }
    }

    private void UpdateChannels(StationModificationInterfaceState state)
    {
        _channelIds.Clear();
        PossibleChannels.Clear();
        foreach (var channel in state.RadioData.Keys)
        {
            if (!_proto.Resolve(channel, out var channelProto))
                continue;

            PossibleChannels.AddItem(channelProto.LocalizedName, _channelIds.Count);
            _channelIds.Add(channel);
        }

        if (_selectedChannel == null || !_channelIds.Contains(_selectedChannel.Value))
            _selectedChannel = _channelIds.Count > 0 ? _channelIds[0] : (ProtoId<RadioChannelPrototype>?) null;

        if (_selectedChannel is { } selected)
            PossibleChannels.SelectId(_channelIds.IndexOf(selected));

        UpdateChannel();
    }

    private void UpdateChannel()
    {
        ChannelAccesses.RemoveAllChildren();
        if (_state == null
            || _selectedChannel is not { } channel
            || !_state.RadioData.TryGetValue(channel, out var data))
        {
            return;
        }

        ChannelEnable.Pressed = data.Enabled;
        ChannelDisable.Pressed = !data.Enabled;

        foreach (var access in _state.CrewAccesses)
        {
            var button = new Button
            {
                Text = access,
                ToggleMode = true,
                ClipText = true,
                HorizontalExpand = true,
                Pressed = data.Access.Contains(access),
            };
            button.OnToggled += args => Send(new StationModificationSetChannelAccess(channel, access, args.Pressed));
            ChannelAccesses.AddChild(button);
        }
    }

    private void UpdateUpgrades(StationModificationInterfaceState state)
    {
        AccountBalanceLabel.Text = Loc.GetString("station-modification-price", ("price", state.AccountBalance));

        if (!_proto.Resolve(state.Level, out var level))
            return;

        CurrentLevelLabel.Text = Loc.GetString(level.Name);
        CurrentBenefitsLabel.SetMarkup(DescribeLevel(level, "station-modification-tile-limit"));

        FactionLevelPrototype? next = null;
        if (level.Next is { } nextId)
            _proto.Resolve(nextId, out next);

        PurchaseLabel.Visible = next != null;
        LevelPurchaseButton.Visible = next != null;
        if (next == null)
        {
            NextLevelLabel.Text = Loc.GetString("station-modification-max-level");
            NextBenefitsLabel.SetMarkup(Loc.GetString("station-modification-max-level-desc"));
            return;
        }

        NextLevelLabel.Text = Loc.GetString(next.Name);
        NextBenefitsLabel.SetMarkup(DescribeLevel(next, "station-modification-next-tile-limit"));
        LevelPurchaseButton.Text = Loc.GetString("station-modification-price", ("price", next.Cost));
        LevelPurchaseButton.Disabled = state.AccountBalance < next.Cost;
    }

    private static string DescribeLevel(FactionLevelPrototype level, string tileLimitLoc)
    {
        var desc = Loc.GetString(tileLimitLoc, ("limit", level.TileLimit));
        if (level.TradestationClaim)
            desc += "\n" + Loc.GetString("station-modification-trade-station");

        return desc;
    }
}
